name: "dbt_transforms"
version: "1.0.0"
config-version: 2

profile: "dbt_transforms"

# Add this line to change the packages installation path
packages-install-path: "/home/airflow/dbt-packages" # Outside the mounted volume

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_transforms:
    marts:
      +materialized: table
